---
name: Molecule Image Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        image:
          - name: debian
            tag: buster
          - name: debian
            tag: stretch
          - name: centos
            tag: 8
          - name: centos
            tag: 7
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install pytest testinfra
      - name: build images
        run: docker build -f ${{ matrix.image.name }}.Dockerfile --build-arg IMAGE=${{ matrix.image.name }} --build-arg TAG=${{ matrix.image.tag }} -t nbjwl/molecule:${{ matrix.image.name }}.${{ matrix.image.tag }}  .
      - name: run test
        run: py.test --image=${{ matrix.image.name }} --tag=${{ matrix.image.tag }} tests/testimage.py
      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_USER_PASSWORD }}
          docker push nbjwl/molecule:${{ matrix.image.name }}.${{ matrix.image.tag }}





