---
name: Molecule Image Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        image:
          - name: debian
            tag: buster
          - name: debian
            tag: stretch
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install docker
      - name: build images
        run: docker build --build-arg IMAGE=${{ matrix.image.name }} --build-arg TAG=${{ matrix.image.tag }} -t nbjwl/molecule:${{ matrix.image.name }}.${{ matrix.image.tag }}  .
      - name: publish
        if: github.event_name == 'push' and github.ref == 'master'
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_USER_PASSWORD }}
          docker push nbjwl/molecule:${{ matrix.image.name }}.${{ matrix.image.tag }}





